/*
  The types used to perform actions
*/
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const VALID_TRANSACTION = 'VALID_TRANSACTION';
export const REMOVE_ERRORS = 'REMOVE_ERRORS';
export const INVALID_TRANSACTION = 'INVALID_TRANSACTION';
export const BATCH_TRANSACTIONS = 'BATCH_TRANSACTIONS';
export const FIELD_BATCH_TRANSACTIONS = 'FIELD_BATCH_TRANSACTIONS';

